cols = [
    'ai_tag',
    'ai_region',
    'ai_org',
    'article_id',
    'content',
    'country',
    'creator',
    'image_url',
    'keywords',
    'language',
    'pubDateTZ',
    'sentiment_stats',
    'source_icon',
    'source_id',
    'source_priority',
    'source_url',
    'video_url',
    # 'duplicate'
]
