name: Daily Newsletter Dispatch

# Cron job runs every morning UTC at 2:30 AM Mon-Sat
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Specify the environment to use"
        required: false
        default: "production"
        type: string
  schedule:
    - cron: "30 2 * * 1-6"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check if Docker image exists locally
        run: |
          if ! docker inspect ${{ vars.DOCKER_USERNAME }}/the-india-story:latest > /dev/null 2>&1; then
            echo "Image not found locally, pulling from Docker Hub..."
            docker pull ${{ vars.DOCKER_USERNAME }}/the-india-story:latest
          else
            echo "Image found locally, using cached version."
          fi

      - name: Logout from Docker Hub
        run: docker logout

      - name: Run Docker container with environment variables
        run: |
          docker run --rm \
            -e NEWSDATAIO_API_KEY=${{ secrets.NEWSDATAIO_API_KEY }} \
            -e NEWSDATAIO_API_KEY_2=${{ secrets.NEWSDATAIO_API_KEY_2 }} \
            -e NEWSDATAIO_API_KEY_3=${{ secrets.NEWSDATAIO_API_KEY_3 }} \
            -e NEWSDATAIO_API_KEY_4=${{ secrets.NEWSDATAIO_API_KEY_4 }} \
            -e NEWSDATAIO_API_KEY_5=${{ secrets.NEWSDATAIO_API_KEY_5 }} \
            -e BREVO_API_KEY=${{ secrets.BREVO_API_KEY }} \
            -e INDIA_STORY_API_KEY=${{ secrets.INDIA_STORY_API_KEY }} \
            -e VERCEL_ACCESS_TOKEN=${{ secrets.VERCEL_ACCESS_TOKEN }} \
            -e ENVIRONMENT=${{ github.event.inputs.environment || 'production' }} \
            ${{ vars.DOCKER_USERNAME }}/the-india-story:latest
