name: Docker Image CI

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "requirements.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%d-%m-%y')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/the-india-story:latest,${{ vars.DOCKER_USERNAME }}/the-india-story:${{ env.DATE }}

      - name: Logout from Docker Hub
        run: docker logout
